# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/OnePlusN200TMO/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),OnePlusN200TMO)

endif
